# Generated by Django 5.0.1 on 2024-01-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
